<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bitbound.Analyzers.MemberOrder" Version="1.0.52">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Bitbound.SystemAbstractions" Version="1.0.7" />
    <PackageVersion Include="Bitbound.SystemAbstractions.TestUtilities" Version="1.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="ModelContextProtocol" Version="2.2.0" />
    <PackageVersion Include="SkiaSharp" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux.Bundled" Version="3.119.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.runner.console" Version="4.0.1" />
  </ItemGroup>
</Project>