<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bitbound.Analyzers.MemberOrder" Version="1.0.52">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="ModelContextProtocol" Version="1.0.0" />
    <PackageVersion Include="SkiaSharp" Version="3.119.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.119.0" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux.Bundled" Version="3.119.0" />
  </ItemGroup>
</Project>