<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bitbound.ImageEditMcp</RootNamespace>
    <AssemblyName>Bitbound.ImageEditMcp</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>bitbound.png</PackageIcon>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>image-edit-mcp</ToolCommandName>
    <PackageId>Bitbound.ImageEditMcp</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\.assets\bitbound.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bitbound.Analyzers.MemberOrder">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Bitbound.SystemAbstractions" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>

</Project>